### PR TITLE
Adds additional tables to mmsdm.py

### PR DESCRIPTION
**Pull request by jnh277**
Adds tables for
- 30 minute predispatch price 
- 5 minute predispatch price
- 5 minute predispatch demand
- 30 minute predispatch demand
- 30 minute predispatch price sensitivities

### CODE REVIEW

**Comment by ADGEfficiency** [comment]
@jnh277 - thank you for the contribution :tada:

Can you add some tests for these new tables in https://github.com/ADGEfficiency/nem-data/blob/ff138d3f62ed398bb8c07e8a0e98a8dfe09c3ab1/tests/test_loader.py

Something along the lines of:

```python

def test_loader_unit_scada(base_dir: pathlib.Path) -> None:
    download("2020-01", "2020-01", "unit-scada", base_directory=base_dir)
    data = load(base_directory=base_dir)["unit-scada"]
    assert data["interval-start"].min() == pd.Timestamp("2020-01-01T00:00:00+1000")
    assert data["interval-start"].max() == pd.Timestamp("2020-01-31T23:55:00+1000")
```

`base_dir` is a `pytest` fixture in a temporary directory.

**Comment by jnh277** [comment]
Yeap, i'll do that tomorrow. I should have done it before. Sorry about that

**Comment by jnh277** [comment]
tests added

**Comment by ADGEfficiency** [comment]
> Yeap, i'll do that tomorrow. I should have done it before. Sorry about that

No need to apologize - you've done well to contribute as there is 0 documentation around how to do so.

**Pull request merged**
